server:
  port: 80
spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  jms:
    pub-sub-domain: false   # 配置消息的类型，如果是true则表示为topic消息，如果为false表示Queue消息
  activemq:
    user: system    # 连接用户名
    password: manager   # 连接密码
    broker-url: tcp://127.0.0.1:61616 # 消息组件的连接主机信息